"use client";

import { useEffect, useRef } from "react";

/**
 * Scroll-scrubbed frame sequence (Atelier scrollytelling primitive).
 * Frames: public/frames/story/frame_001.webp … generated by the asset pipeline.
 * Reduced motion is handled at the call site — it renders a static poster.
 */
export function ScrollScrub({
  dir,
  count,
  pad = 3,
  className = "",
  children,
}: {
  dir: string;
  count: number;
  pad?: number;
  className?: string;
  children?: React.ReactNode;
}) {
  const wrap = useRef<HTMLDivElement>(null);
  const canvas = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const imgs = Array.from({ length: count }, (_, i) => {
      const img = new Image();
      img.src = `${dir}/frame_${String(i + 1).padStart(pad, "0")}.webp`;
      return img;
    });
    const ctx = canvas.current!.getContext("2d")!;
    let current = -1;
    let queued = false;

    const draw = (i: number) => {
      const img = imgs[i];
      if (!img?.complete || i === current) return;
      current = i;
      canvas.current!.width = img.naturalWidth;
      canvas.current!.height = img.naturalHeight;
      ctx.drawImage(img, 0, 0);
    };

    const onScroll = () => {
      if (queued) return;
      queued = true;
      // Coalesce to one paint per frame — scroll fires far faster than 60Hz.
      requestAnimationFrame(() => {
        queued = false;
        const el = wrap.current;
        if (!el) return;
        const span = el.scrollHeight - innerHeight;
        const p = span > 0 ? -el.getBoundingClientRect().top / span : 0;
        draw(Math.min(count - 1, Math.max(0, Math.round(p * (count - 1)))));
      });
    };

    imgs[0].onload = () => draw(0);
    addEventListener("scroll", onScroll, { passive: true });
    onScroll();
    return () => removeEventListener("scroll", onScroll);
  }, [dir, count, pad]);

  return (
    <div ref={wrap} className={className}>
      <div className="sticky top-0 h-screen overflow-hidden">
        <canvas ref={canvas} className="h-full w-full object-cover" />
        {children}
      </div>
    </div>
  );
}
